WebApplication1/Controllers/AllocationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebApplication1.Data;
using WebApplication1.Models;
using WebApplication1.Repository.Interface;
using WebApplication1.Service;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AllocationController : Controller
    {
        private readonly IApplicationUserRepositoryAsync _applicationUser;
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRazorRenderService _renderService;
        private readonly ILogger<UserManageController> _logger;
        private readonly ApplicationDbContext _context;

        public AllocationController(ILogger<UserManageController> logger
            , ApplicationDbContext context
            , IApplicationUserRepositoryAsync applicationUser
            , UserManager<ApplicationUser> userManager
            , IUnitOfWork unitOfWork
            , IRazorRenderService renderService)
        {
            _logger = logger;
            _context = context;
            _applicationUser = applicationUser;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _renderService = renderService;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/FormDefinitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class FormDefinitionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Detail()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/TmpController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TmpController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;

        public TmpController(ILogger<HomeController> logger, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

WebApplication1/Controllers/UserManageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CsvHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebApplication1.Data;
using WebApplication1.Models;
using WebApplication1.Repository.Interface;
using WebApplication1.Service;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserManageController : Controller
    {
        private readonly IApplicationUserRepositoryAsync _applicationUser;
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRazorRenderService _renderService;
        private readonly ILogger<UserManageController> _logger;
        private readonly ApplicationDbContext _context;

        public UserManageController(ILogger<UserManageController> logger
            , ApplicationDbContext context
            , IApplicationUserRepositoryAsync applicationUser
            , UserManager<ApplicationUser> userManager
            , IUnitOfWork unitOfWork
            , IRazorRenderService renderService)
        {
            _logger = logger;
            _context = context;
            _applicationUser = applicationUser;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _renderService = renderService;
        }
        public IEnumerable<ApplicationUser> applicationUsers { get; set; }
        public List<SelectListItem> IsValidList = new List<SelectListItem>
{
        new SelectListItem { Value = "",Text = ""},
        new SelectListItem { Value = "表示",Text = "表示"},
        new SelectListItem { Value = "非表示",Text = "非表示"},
    };
        public async Task<IActionResult> Index()
        {
            ViewBag.Roles = RoleViewModel.GetSelectList();
            ViewBag.UserGroups = UserGroupViewModel.GetSelectList();
            ViewBag.IsValidList = IsValidList;
            var users = await ApplicationUserViewModel.GetAll(_context, _applicationUser);

            return View(users);
        }

        public IActionResult BulkRegist()
        {
            return View();
        }

        public IActionResult SikenKanri()
        {
            return View();
        }

        public async Task<IActionResult> GetTemplateFile()
        {
            // CSV ファイル名
            string csvFileName = "【アップロード用】ユーザーデータ.csv";
            // メモリを確保する
            using (var memory = new MemoryStream())
            using (var writer = new StreamWriter(memory, Encoding.GetEncoding("shift-jis")))
            using (var csv = new CsvWriter(writer, new CultureInfo(0x0411, false)))
            {
                var applicationUsers = await ApplicationUserViewModel.GetAll(_context, _applicationUser);
                csv.WriteRecords(applicationUsers);
                writer.Flush();
                // CSVファイルとして出力する
                return File(memory.ToArray(), "text/csv", csvFileName);
            }
        }



        public async Task<IActionResult> OnGetViewAllPartial()
        {
            var users = await ApplicationUserViewModel.GetAll(_context, _applicationUser);
            return new PartialViewResult
            {
                ViewName = "_ViewAll",
                ViewData = new ViewDataDictionary<IEnumerable<ApplicationUserViewModel>>(ViewData, users)
            };
        }

        public async Task<IActionResult> GetCreateOrEdit(string id = null)
        {
            ViewBag.Roles = RoleViewModel.GetSelectList();
            ViewBag.UserGroups = UserGroupViewModel.GetSelectList();
            ViewBag.IsValidList = IsValidList;

            if (string.IsNullOrEmpty(id))
            {
                return PartialView("_CreateOrEdit", new ApplicationUserViewModel());
            }
            else
            {
                var u = await ApplicationUserViewModel.Get(_context, _applicationUser, id);
                return PartialView("_CreateOrEdit", u);
            }
        }
        public async Task<IActionResult> CreateOrEdit(string id, ApplicationUserViewModel applicationUser)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(id))
                {
                    var user = new ApplicationUser
                    {
                        UserName = applicationUser.UserId,
                        DisplayUserName = applicationUser.DisplayUserName,
                        GroupName = applicationUser.GroupName,
                        Password = applicationUser.Password,
                        IsValid = applicationUser.IsValid
                    };

                    var result = await _userManager.CreateAsync(user, applicationUser.Password);
                    user = _context.Users.First(x => x.UserName == applicationUser.UserId);
                    _context.UserRoles.Add(new IdentityUserRole<string> { RoleId = applicationUser.UserRoleId, UserId = user.Id });
                    await _context.SaveChangesAsync();

                }
                else
                {
                    var user = _context.Users.First(x => x.Id == id);
                    user.UserName = applicationUser.UserId;
                    user.DisplayUserName = applicationUser.DisplayUserName;
                    user.GroupName = applicationUser.GroupName;
                    user.Password = applicationUser.Password;
                    user.PasswordHash = _userManager.PasswordHasher.HashPassword(user, applicationUser.Password);
                    user.IsValid = applicationUser.IsValid;

                    _context.Users.Update(user);

                    var role = _context.UserRoles.First(x => x.UserId == id);
                    _context.UserRoles.Remove(role);
                    _context.UserRoles.Add(new IdentityUserRole<string> { RoleId = applicationUser.UserRoleId, UserId = applicationUser.Id });

                    await _context.SaveChangesAsync();
                }

                return await OnGetViewAllPartial();
            }
            else
            {
                return await OnGetViewAllPartial();
            }
        }
        public async Task<IActionResult> Delete(string id)
        {
            var applicationUser = await _context.Users.FirstAsync(x => x.Id == id);
            await _applicationUser.DeleteAsync(applicationUser);
            var role = _context.UserRoles.First(x => x.UserId == id);
            _context.UserRoles.Remove(role);
            await _unitOfWork.Commit();
            return await OnGetViewAllPartial();
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Checkmates</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/font-awesome-animation/font-awesome-animation.min.css" type="text/css" media="all" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Checkmates</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserManage" asp-action="Index">ユーザー管理</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Allocation" asp-action="Index">採点者振り分け</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tmp" asp-action="Index">データ登録</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="FormDefinition" asp-action="Index">帳票定義</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" id="form-modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Description Checkmates - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>